# Generated by Django 4.2 on 2023-04-21 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('price', models.FloatField(default=0.0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('editing', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=60)),
                ('position', models.CharField(choices=[('DI', 'Директор'), ('AD', 'Администратор'), ('LJ', 'Ведущий журналист'), ('JO', 'Журналист'), ('ED', 'Редактор')], default='JO', max_length=2)),
                ('employment_contract', models.IntegerField()),
                ('phone', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubric', models.CharField(max_length=30)),
                ('article_title', models.CharField(max_length=35)),
                ('article_text', models.TextField()),
                ('views', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SectionArticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('articles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_sections.section')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_sections.articles')),
            ],
        ),
        migrations.AddField(
            model_name='articles',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news_sections.author'),
        ),
        migrations.AddField(
            model_name='articles',
            name='section',
            field=models.ManyToManyField(through='news_sections.SectionArticles', to='news_sections.section'),
        ),
    ]
