# Generated by Django 4.2 on 2023-04-22 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_sections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionarticles',
            name='articles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_sections.articles'),
        ),
        migrations.AlterField(
            model_name='sectionarticles',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_sections.section'),
        ),
    ]
